
export interface Message {
  id: string;
  text: string;
  sender: 'user' | 'ai';
  timestamp: number; // Using number for Date.now() for simplicity, can be Date object
  user_id?: string; // ID của user
  session_id?: string; // ID của phiên chat
}

// Interface cho tin nhắn trong database
export interface ChatMessage {
  id: string;
  user_id: string;
  message_text: string;
  sender: 'user' | 'ai';
  timestamp: string; // ISO string từ database
  session_id?: string;
  created_at?: string;
  updated_at?: string;
}

export interface PayrollEntry {
  employee_id: string;
  employee_name: string;
  salary: number;
  pay_date: string; // Assuming YYYY-MM-DD format for date
}

// For Supabase, it often includes id and created_at
export interface SupabasePayrollEntry extends PayrollEntry {
  id?: string; // Optional as it's auto-generated by Supabase on insert
  created_at?: string; // Optional as it's auto-generated by Supabase
}

export interface SupabaseTable {
  table_name: string;
}

export type DataRow = Record<string, any>;

export interface OrgNode {
  id: string;
  name: string; // Department name
  parent_id: string | null;
  children: OrgNode[];
}

export interface FlatOrgUnit {
  ID: string;
  Parent_ID: string | null;
  Department: string;
}

