
export interface Message {
  id: string;
  text: string;
  sender: 'user' | 'ai';
  timestamp: number; // Using number for Date.now() for simplicity, can be Date object
}

export interface PayrollEntry {
  employee_id: string;
  employee_name: string;
  salary: number;
  pay_date: string; // Assuming YYYY-MM-DD format for date
}

// For Supabase, it often includes id and created_at
export interface SupabasePayrollEntry extends PayrollEntry {
  id?: string; // Optional as it's auto-generated by Supabase on insert
  created_at?: string; // Optional as it's auto-generated by Supabase
}

export interface SupabaseTable {
  table_name: string;
}
